DROP TABLE book IF EXISTS;

CREATE TABLE book (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title varchar(255) NOT NULL,
  author varchar(255),
  PRIMARY KEY (id)
);

INSERT INTO book (id, title, author) VALUES (1, 'title', 'author');
